-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 19, 2021 at 12:52 AM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `clean-blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(211) NOT NULL,
  `slug` varchar(211) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Test category', 'test-category', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(2, 'Category 1', 'çategory-1', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(3, 'Category 2', 'category-2', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(4, 'Test category', 'test-category21', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(5, 'Category 121', 'çategory-121', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(6, 'Category 221', 'category-221', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(7, 'Test category21', 'test-category211', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(8, 'Category 132', 'çategory-132', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(9, 'Category 232', 'category-232', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(10, 'Test category32', 'test-category2132', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(11, 'Category 12132', 'çategory-12132', '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(12, 'Category 22132', 'category-22132', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

-- --------------------------------------------------------

--
-- Table structure for table `favourite_posts`
--

CREATE TABLE `favourite_posts` (
  `id` int(11) NOT NULL,
  `post_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `favourite_posts`
--

INSERT INTO `favourite_posts` (`id`, `post_id`, `user_id`) VALUES
(4, 6, 1),
(5, 9, 1),
(9, 2, 1);

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(11) UNSIGNED NOT NULL,
  `title` varchar(211) NOT NULL,
  `slug` varchar(211) NOT NULL,
  `user_id` int(11) UNSIGNED NOT NULL,
  `category_id` int(11) UNSIGNED NOT NULL,
  `tag_id` int(11) UNSIGNED NOT NULL,
  `featured_image` varchar(211) NOT NULL,
  `excerpt` text NOT NULL,
  `content` text NOT NULL,
  `views` int(11) NOT NULL DEFAULT 0,
  `featured` int(11) NOT NULL DEFAULT 0,
  `soft_deleted` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `slug`, `user_id`, `category_id`, `tag_id`, `featured_image`, `excerpt`, `content`, `views`, `featured`, `soft_deleted`, `created_at`, `updated_at`) VALUES
(1, 'Post title', 'Post-title', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(2, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulcet-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(3, 'Post title', 'Post-title12', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(4, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(5, 'Post title', 'Post-title21212', 1, 9, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(6, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulcet-sensu21212m-voluptate-', 1, 9, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(7, 'Post title', 'Post-title122121212', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(8, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-p21323123123ermulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(9, 'Post title', 'Post-title3213123132', 1, 6, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(10, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-32312312312qui-permulcet-sensum-voluptate-', 1, 6, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(11, 'Post title', 'Post-title12323123123123', 1, 5, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(12, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(13, 'Post title', 'Post-title21212', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(14, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulcet-sensu21212m-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(15, 'Post title', 'Post-title122121212', 1, 9, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(16, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-p21323123123ermulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(17, 'Post title', 'Post-title', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(18, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulcet-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(19, 'Post title', 'Post-title12', 1, 9, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(20, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulce21t-sensum-voluptate-', 1, 9, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(21, 'Post title', 'Post-title21212', 1, 9, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(22, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulcet-sensu21212m-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(23, 'Post title', 'Post-title122121212', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(24, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-p21323123123ermulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(25, 'Post title', 'Post-title3213123132', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(26, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-32312312312qui-permulcet-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(27, 'Post title', 'Post-title12323123123123', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(28, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(29, 'Post title', 'Post-title21212', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(30, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-permulcet-sensu21212m-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21'),
(31, 'Post title', 'Post-title122121212', 1, 1, 3, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzDpyXT73yJQS_rAFLSNe_hZF4YkwQZ7r4nA&usqp=CAU', 'This is post excerpt', 'This is post content', 1233, 1, 0, '2021-03-13 12:47:44', '2021-03-13 12:47:44'),
(32, 'At ille pellit, qui permulcet sensum voluptate.', 'At-ille-pellit-qui-p21323123123ermulce21t-sensum-voluptate-', 1, 1, 3, 'http://milanjankovic.in.rs/images/image.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra</p>', '<h2>At ille pellit, qui permulcet sensum voluptate.</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Sed plane dicit quod intellegit.</strong> Teneo, inquit, finem illi videri nihil dolere. Quod cum dixissent, ille contra.</p><p><a href=\"http://loripsum.net/\">Cum praesertim illa perdiscere ludus esset.</a> Quid me istud rogas? Ut pulsi recurrant? Ita credo. Istam voluptatem, inquit, Epicurus ignorat? <i>Quid enim possumus hoc agere divinius?</i> Beatus sibi videtur esse moriens.</p><p>Respondeat totidem verbis.</p><p>Et hunc idem dico, inquieta sed ad virtutes et ad vitia nihil interesse.</p><p>Nulla erit controversia.</p><p>Eam tum adesse, cum dolor omnis absit;</p><p>Quibusnam praeteritis?</p><p>Aliter homines, aliter philosophos loqui putas oportere?</p><ol><li>Respondent extrema primis, media utrisque, omnia omnibus.</li><li>Commentarios quosdam, inquam, Aristotelios, quos hic sciebam esse, veni ut auferrem, quos legerem, dum essem otiosus;</li><li>Is ita vivebat, ut nulla tam exquisita posset inveniri voluptas, qua non abundaret.</li><li>Nisi autem rerum natura perspecta erit, nullo modo poterimus sensuum iudicia defendere.</li><li>Uterque enim summo bono fruitur, id est voluptate.</li></ol><p>Illi enim inter se dissentiunt. Sed ad rem redeamus; <strong>Sed haec in pueris;</strong> <a href=\"http://loripsum.net/\">Illi enim inter se dissentiunt.</a> Qua tu etiam inprudens utebare non numquam. Equidem etiam Epicurum, in physicis quidem, Democriteum puto.</p><ul><li>Quodsi ipsam honestatem undique pertectam atque absolutam.</li><li>Haec mihi videtur delicatior, ut ita dicam, molliorque ratio, quam virtutis vis gravitasque postulat.</li></ul><p>Ergo illi intellegunt quid Epicurus dicat, ego non\r\nintellego?\r\n\r\nSi longus, levis.\r\n</p><p>Expectoque quid ad id, quod quaerebam, respondeas. Recte, inquit, intellegis. Quamquam in hac divisione rem ipsam prorsus probo, elegantiam desidero. Duo Reges: constructio interrete.</p><blockquote><p>Crasso, quem semel ait in vita risisse Lucilius, non contigit, ut ea re minus agelastoj ut ait idem, vocaretur.&nbsp;</p></blockquote><h2>Qui est in parvis malis.</h2><p>Sed haec omittamus; Duo enim genera quae erant, fecit tria. Sit hoc ultimum bonorum, quod nunc a me defenditur; <i>Nos cum te, M.</i></p>', 0, 1, 0, '2021-03-14 20:51:21', '2021-03-14 20:51:21');

-- --------------------------------------------------------

--
-- Table structure for table `tags`
--

CREATE TABLE `tags` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(211) NOT NULL,
  `slug` varchar(211) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tags`
--

INSERT INTO `tags` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Tag 1', 'Tag-1', '2021-03-12 11:26:59', '2021-03-12 11:26:59'),
(2, 'Tag 23', 'Tag-23', '2021-03-12 11:27:30', '2021-03-12 11:27:30'),
(3, 'My  tag', 'My-tag', '2021-03-12 11:30:45', '2021-03-12 11:30:45'),
(4, 'csacascacsc', 'csacascacsc', '2021-03-13 22:27:43', '2021-03-13 22:27:43'),
(5, 'cacascbztum6kj,l,7', 'cacascbztum6kj-l-7', '2021-03-13 22:32:41', '2021-03-13 22:32:41');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(211) NOT NULL,
  `slug` varchar(211) NOT NULL,
  `email` varchar(211) NOT NULL,
  `password` varchar(211) NOT NULL,
  `is_admin` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `banned` int(11) NOT NULL DEFAULT 0,
  `active` int(11) NOT NULL DEFAULT 1,
  `ip_address` varchar(211) NOT NULL,
  `featured_image` varchar(211) DEFAULT 'https://usapng.com/images/thumb/200_/user-icon-6.webp',
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `slug`, `email`, `password`, `is_admin`, `banned`, `active`, `ip_address`, `featured_image`, `created_at`, `updated_at`) VALUES
(1, 'Milan Janković', '', 'milanj31@gmail.com', '$2y$10$nyMh9rq1hjW/abVlZVB3eOkNlC98y2wN43LWF66sJg.htozGVgU2C', 1, 0, 1, '::1', 'https://usapng.com/images/thumb/200_/user-icon-6.webp', '2021-03-18 04:03:05', '2021-03-18 04:03:05'),
(5, 'Test user', '', 'test@gmail.com', '$2y$10$CfP7yjdOA1R.NOITgqkiDejylsf.EnMYHR9zt5DJSE.6Imi3HnPai', 0, 0, 1, '::1', 'https://usapng.com/images/thumb/200_/user-icon-6.webp', '2021-03-18 21:43:25', '2021-03-18 21:43:25');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `favourite_posts`
--
ALTER TABLE `favourite_posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tags`
--
ALTER TABLE `tags`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQUE` (`slug`),
  ADD UNIQUE KEY `slug` (`slug`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `favourite_posts`
--
ALTER TABLE `favourite_posts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT for table `tags`
--
ALTER TABLE `tags`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
